### ISSUE TITLE
Conflicting behavior between the Hetzner load balancer's hostname annotation and Node.js Neo4j driver's connection URL

### ISSUE THREAD

**Issue by vinnytwice** [neo4j/helm-charts#208]
I'm creating a Kubernetes cluster on Hetzner Cloud with the same configuration I use on Azure AKS but I'm facing connection problems with Neo4j Community.
On Hetzner cluster while I can access Neo4J browser from the path I defined in my Ingress, I can't connect to the Neo4j server using the bolt+s connection server.mydomain.com:7687 URL, nor does the Neo4j driver in my Node.js server pod (this second connection is kinda solved, as found out toward the end).
This is not the case with the AKS cluster.

From Neo4j Browser debbug connection I see that the Handshake fails:
```
Browser will attempt to open a websocket connection to bolt+s://server.mydomain.com:7687 and do an encrypted and an unencrypted bolt handshake.
bolt handshake
Status: 
Error
encrypted bolt handshake
Status: 
Error
```
From Chrome console I see 2 errors:
```
Mixed Content: The page at 'https://server.mydomain.com/neo4j/browser/' was loaded over HTTPS, but requested an insecure resource 'http://server.mydomain.com:7687/'. This request has been blocked; the content must be served over HTTPS.

WebSocket connection to 'wss://server.mydomain.com:7687/' failed:
``` 
The one difference between the two clusters is the ingress controller's Load Balancer configuration for which on Hetzner I set annotations in the ingress-nginx Helm chart as so:
```
nginx:
  controller:
    watchIngressWithoutClass: true
    kind: DaemonSet
    config:
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      use-proxy-protocol: "true"
    service:
      annotations:
        load-balancer.hetzner.cloud/name: server-lb
        load-balancer.hetzner.cloud/use-private-ip: "true"
        load-balancer.hetzner.cloud/disable-private-ingress: "true"
        load-balancer.hetzner.cloud/location: fsn1
        load-balancer.hetzner.cloud/type: lb11
        load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
        load-balancer.hetzner.cloud/http-redirect-https: "true"
        load-balancer.hetzner.cloud/hostname: server.mydomain.com
        # nginx.ingress.kubernetes.io/websocket-services: neo4j

    extraArgs:
      default-ssl-certificate: "default/tls-secret"  

    # nodeSelector:
    #   server-type: server  
  tcp:
    7687: "default/neo4j:7687" 
    7474: "default/neo4j:7474"
```
AFAIK `ingress-nginx` controller (which I'm using) handles WebSockets automatically unlike `nginx-ingress` for which should be mapped to a service using an annotation like `nginx.ingress.kubernetes.io/websocket-services: neo4j`, I tried using the annotation anyways but didn't make a difference.
   

The complete procedure I used for the Hetzner cluster is:
I created a Kubernetes a single node cluster on Hetzner Cloud using k3s v1.27.4+k3s1, installed ingress-nginx v4.7.1 exposing TCP ports 7474 and 7687 to neo4j service as shown above (the Load Balancer TCP ports are exposed and healthy) and Cert-manager v1.12.3 Helm charts.
 

In my domain DNS manager I created an A record pointing to the load balancer IPv4 with host set as `sever` to use it in my `Certificate` and `Ingress` manifests as `server.mydomain.com`. The `tls-secret` used both in `Ingress` and `Neo4j` ssl configuration gets created correctly.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$2$3$4
    ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes/cluster-issuer: letsencrypt-issuer

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - server.mydomain.com
      secretName: tls-secret
  rules:

    ### Node.js server
    - http:
        paths:
          - path: /(/|$)(.*)
            # pathType: Prefix
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-clusterip-service
                port:
                  number: 80
    - http:
        paths:
          - path: /server(/|$)(.*)
            # pathType: Prefix
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-clusterip-service
                port:
                  number: 80

    ##### Neo4j

    - http:
        paths:
          - path: /bolt(/|$)(.*)
            # pathType: Prefix
            pathType: ImplementationSpecific
            backend:
              service:
                name: neo4j
                port:
                  number: 7687
    - http:
        paths:
          # show browser
          - path: /neo4j(/|$)(.*)
            # pathType: Prefix
            pathType: ImplementationSpecific
            backend:
              service:
                name: neo4j
                port:
                  number: 7474
    - http:
        paths:
          - path: /neo4j-admin(/|$)(.*)
            # pathType: Prefix
            pathType: ImplementationSpecific
            backend:
              service:
                name: neo4j-admin
                port:
                  number: 7474
```

To install Neo4j chart I'm setting these values for Neo4j configuration:
```
  config:
    server.bolt.enabled: 'true'
    server.bolt.tls_level: 'REQUIRED'
    server.bolt.listen_address: '0.0.0.0:7687'
    dbms.ssl.policy.bolt.client_auth: 'NONE'
    dbms.ssl.policy.bolt.enabled: 'true'

    # dbms.connector.bolt.advertised_address: '0.0.0.0:7687' #server.mydomain.com:7687 # new for hetzner (no connection still)

    ## apoc
    server.directories.plugins: '/var/lib/neo4j/labs'
    dbms.security.procedures.unrestricted: 'apoc.*'
    server.config.strict_validation.enabled: 'false'
    dbms.security.procedures.allowlist: 'gds.*,apoc.*'

    ### apoc config
    dbms.directories.plugins: "/var/lib/neo4j/labs"
    dbms.config.strict_validation: "false"



  apoc_config:
    apoc.trigger.enabled: "true"
    apoc.jdbc.neo4j.url: "jdbc:foo:bar"
    apoc.import.file.enabled: "true"

  startupProbe:
    failureThreshold: 1000
    periodSeconds: 50

  ssl:
    # setting per "connector" matching neo4j config
    bolt:
      privateKey:
        secretName: tls-secret
        subPath: tls.key
      publicCertificate:
        secretName: tls-secret
        subPath: tls.crt
      trustedCerts:
        sources: []
      revokedCerts:
        sources: []
```
I tried setting the `dbms.connector.bolt.advertised_address`(dough on Azure is not set) using both the any IP `0.0.0.0:7687` value and the specific dns `server.mydomain.com:7687`value but that didn't make a difference either.
On the Hetzner Firewall rules I created rules for ports 80(http) and 443 (https) to allow to ports 7474 and 7687. I also tried disabling the Firewall as a test but still can't reach Neo4j server.

I noticed that the nginx-ingress-controller External IP onAzure was actually showing the IPv4 address from the load balancer, while on Hetzner it was showing the dns name `server.mydomain.com` so I removed the `load-balancer.hetzner.cloud/hostname: server.mydomain.com` annotation from `ingress-nginx` service annotations helm chart and without it the Neo4j driver in my Node.js server pod succeeds in connecting to Neo4j.

Unfortunately I still get the following two errors when connecting from the Neo4j Browser app on the web browser:
```
Mixed Content: The page at 'https://server.mydomain.com/neo4j/browser/' was loaded over HTTPS, but requested an insecure resource 'http://server.mydomain.com:7687/'. This request has been blocked; the content must be served over HTTPS.

WebSocket connection to 'wss://server.mydomain.com:7687/' failed:
```
Started a fresh server on Hetzner Cloud to test the entire installation process, and while issuing the Let'sEncrypt certificate, if I don't use the annotation `load-balancer.hetzner.cloud/hostname: server.mydomain.com`, Certificate issuance hangs, while with it completes as expected.

I'm completely going in circles.
Is there some other configuration I need to add or change for this setup?
Many thanks

Neo4j Helm chart Version: 4.4.21
javascript driver:  ^5.0.1
Operating System: ubuntu-22.04

**Comment by ojhughes** [comment]
Hi @vinnytwice 

This is a known issue - one option is to use a reverse proxy (such as HAProxy) to tunnel 7474 / 7687 on the same port. We don't have any official way to do this yet - there is a draft PR you can take a look at to see an example of some configuration 

https://github.com/neo4j/helm-charts/pull/180/files

**Comment by vinnytwice** [comment]
Hi @ojhughes and thanks for answering this quick! I'm gonna have a look into it dough I don't really master reverse proxy. 
Do you mean that I should I use Haproxy kubernetes-ingress chart instead of ingress-nginx chart as Ingress controller?  
Could you elaborate a bit on why there is the need for the reverse proxy? On Azure cluster I didn't have to do anything special, just installed the ingress-nginx and neo4j-standalone charts. I was using the neo4j-standalone v4.4.16 dough, not the v4.4.21 I'm using now. 
Many thanks again.

**Comment by vinnytwice** [comment]
@ojhughes sorry to bother you this much but I'm really a noob about networking ..
I had a look at the PR you linked and if I got it right `neo4j-database-ingress` is a future neo4j helm chart that installs HAproxy with a setup that does make it tunnel the neo4j service ports as you mentioned above. 

So I either do wait for the`neo4j-database-ingress` chart to be officially published ( can't really do that..) or I do kinda recreate it using the haproxytech `haproxy` chart ( not the `kubernetes-ingress` one right?). 
 
Now the million dollar question..
Do I just install `haproxy` with either of the two methods above or I'd be better off  just replacing ingress-nginx altogether with `kubernetes-ingress`? 

> This is a known issue 

Did you mean on Hetzner Cloud or in which environment/cloud/setup?? ( on Azure AKS I don't have any problem with the current cluster setup ).

Many many thanks again.
Cheers.

**Comment by ojhughes** [comment]
> On Azure cluster I didn't have to do anything special, just installed the ingress-nginx and neo4j-standalone charts

Neo4j Browser does not work out of the box with any Kubernetes ingress implementation, due to the browser requiring 2 ports to operate (7474/7687 by default). The configuration you posted above works around these issues but it looks like there are some differences in networking between AKS and Hertzner. 

The browser *does* work with a regular kubernetes LoadBalancer Service (without Ingress). 

> or I do kinda recreate it using the haproxytech haproxy chart 

That is an option although there will be a learning curve involved

Apologies that we don't have a better answer for you right now! We do hope to provide a much better Ingress experience in the future

**Comment by vinnytwice** [comment]
@ojhughes thanks for answering. 
> On Azure cluster I didn't have to do anything special, just installed the ingress-nginx and neo4j-standalone charts

I meant apart to expose the 2 tcp ports needed for Neo4j Browser, and create 2 paths in the Ingress to serve it.
>or I do kinda recreate it using the haproxytech haproxy chart

>That is an option although there will be a learning curve involved

I sure could use the chart you're putting together, I don't really want to learn HAproxy right now, do you have an estimate on when `neo4j-database-ingress` will be generally available?

**Comment by ojhughes** [comment]
>  do you have an estimate on when neo4j-database-ingress will be generally available?

Unfortunately we don't yet, we still need to agree internally what to do here and the DB Ingress chart is one potential option. There is a lot of momentum for an official ingress solution, so I would hope it won't be too long

**Comment by vinnytwice** [comment]
> we still need to agree internally what to do here and the DB Ingress chart is one potential option

Oh I see, can I ask you what other options are o the table?

Many thanks once again.

**Comment by harshitsinghvi22** [comment]
this is addressed through the new helm chart "neo4j-reverse-proxy". Released for both 5.12.0 and 4.4.26
With this helm chart you can access Neo4j via an ingress on port 80 or 443 (TLS)
https://neo4j.com/docs/operations-manual/5/kubernetes/accessing-neo4j-ingress/
https://neo4j.com/docs/operations-manual/4.4/kubernetes/accessing-neo4j-ingress/

**Comment by vinnytwice** [comment]
@harshitsinghvi22 Nice. Thank you very much. Cheers.

**Comment by vinnytwice** [comment]
@harshitsinghvi22 Hi again.
I'm looking at the new reverse proxy chart and I have a few doubts.
Looking at the chart values I see that many parameters have changed
```
# Default values for neo4j reverse proxy helm chart

## @param nameOverride String to partially override common.names.fullname
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
fullnameOverride: ""

# Parameters for reverse proxy
reverseProxy:
  image: "neo4j/helm-charts-reverse-proxy:5.12.0"

  # Name of the kubernetes service. This service should have the ports 7474 and 7687 open.
  # This could be the admin service ex: "standalone-admin" or the loadbalancer service ex: "standalone" created via the neo4j helm chart
  # serviceName , namespace , domain together will form the complete k8s service url. Ex: standalone-admin.default.svc.cluster.local
  # When used against a cluster ensure the service being used is pointing to all the cluster instances.
  # This could be the loadbalancer from neo4j helm chart or the headless service installed via neo4j-headless-service helm chart
  serviceName: ""
  # default is set to cluster.local
  domain: "cluster.local"

  # This assumes ingress-nginx controller or haproxy-ingress-controller is already installed in your kubernetes cluster.
  # You can install ingress-nginx by following instructions on this link https://github.com/kubernetes/ingress-nginx/blob/main/docs/deploy/index.md#quick-start
  # You can install haproxy-ingress by following instructions on this link https://haproxy-ingress.github.io/docs/getting-started/
  ingress:
    enabled: true
    #default value is nginx. It can be either nginx or haproxy
    className: nginx
    annotations: {}
#      "demo": "value"
#      "demo2": "value2"
    tls:
      enabled: false
      config: []
#      - secretName: "demo2"
#        hosts:
#          - localhost
```


I still see the config which I'd guess should get configured as before for the standalone chart, but I don't see any ssl parameters which I used to configure as:
```
ssl:
    # setting per "connector" matching neo4j config
    bolt:
      privateKey:
        secretName: tls-secret
        subPath: tls.key
      publicCertificate:
        secretName: tls-secret
        subPath: tls.crt
      trustedCerts:
        sources: []
      revokedCerts:
        sources: []
```
How the SSL certificate is now managed? directly from the ingress controller? 

In the manual you linked above I see

>Configure the ingress.yaml file that you will use to install the Reverse proxy Helm chart.


>Configure the ingress.yaml file with the correct values for the serviceName and secretName. Ensure that the secretName is the same as the one created in the previous step. Enable TLS by setting tls.enabled to true.
reverseProxy:
    image: neo4j/helm-charts-reverse-proxy:5.12.0
    serviceName: "standalone-admin"
    ingress:
        enabled: true
        tls:
            enabled: true
            config:
                - secretName: ingress-cert
                  hosts:
                    - localhost
 

If this is the chart's values file, then the `config` param is not for configuring `Neo4j` as before ( eg. `server.bolt.enabled: 'true'` etc.) ,  but to configure the ingress.yaml and looks like `secretName` would substitute the manual bolt configuration shown above, which would clarify how to set up ssl now. If this is the case, are renewed certificates now picked up automatically? (see my other issue here https://github.com/neo4j/helm-charts/issues/247#top)  


Many thanks

**Comment by harshitsinghvi22** [comment]
@vinnytwice the ssl certs are for the neo4j standalone instances and the ssl section in values.yaml is only for neo4j helm chart.
the reverse proxy helm chart does not support any ssl certs..the config.secretName is the kuberenetes secret for ingress certs and not neo4j certs.

neo4j-reverse-proxy helm chart has a separate values.yaml and neo4j helm chart has a separate values.yaml. 

reverse-proxy has nothing to do with ssl certs getting picked up automatically thats a different issue altogether.

If you are using neo4j-reverse-proxy helm chart the ssl terminates at ingress itself with the usage of ingress certs.

**Comment by harshitsinghvi22** [comment]
you can read more here
https://neo4j.com/docs/operations-manual/current/kubernetes/accessing-neo4j-ingress/

**Comment by vinnytwice** [comment]
@harshitsinghvi22 thanks for answering this quick! sorry.. I didn't understand that this is a chart to add to my setup.. I don't know I how, but I thought that this would replace the standalone chart.. 

so to recap..
>if you are using neo4j-reverse-proxy helm chart the ssl terminates at ingress itself with the usage of ingress certs.

By using this reverse proxy I don't need to set endpoints for Neo4j browser anymore as I do in my Ingress above.
Opt.1 - I just use the 443 port of my host. eg example.com:443
Opt.2 - I still set the Ingress as above opening the ports 7687 and 7474 of the ingress controller and access Neo4j Browser at `example.com/neo4j/browser/` as I did before.  

>the reverse proxy helm chart does not support any ssl certs..the config.secretName is the kuberenetes secret for ingress certs and not neo4j certs.

In my case I use the same cert and I use the bolt connector for the neo4j javascript driver, so I guess Opt 2 is still the preferred setup so the uri for the Neo4j driver will be `example.com/bolt:7687` 

Did you have a chance to see my other issue  https://github.com/neo4j/helm-charts/issues/247#top?
Many thanks again.

**Comment by harshitsinghvi22** [comment]
@vinnytwice lets not combine two different issues. I will comment on the issue #247 on the issue itself.

With the reverse proxy helm chart you do not have to set any endpoints with the ingress. The helm chart itself creates an ingress which allows two ports 80/443 which then redirects traffic to 7687 and 7474.

I would highly suggest going through the documentation
https://neo4j.com/docs/operations-manual/current/kubernetes/accessing-neo4j-ingress/

**Comment by vinnytwice** [comment]
@harshitsinghvi22 thanks again for the quick reply.
>lets not combine two different issues. I will comment on the issue https://github.com/neo4j/helm-charts/issues/247 on the issue itself.

sure, I was just asking as you've been very helpful on this new comment and the other comment is from a couple of days ago.

>The helm chart itself creates an ingress which allows two ports 80/443 which then redirects traffic to 7687 and 7474.

So I won't be able to use the Ingress `I created`.
I should then avoid opening the ingress controller tcp ports and setting dedicated endpoints for Neo4j, plus I have to  update the Neo4j JS driver url to the new ingress host and port eg. `example.com:443` correct ?

>I would highly suggest going through the documentation

That's where parts of it confused me, for example
>Install the Reverse proxy Helm chart
Install the Reverse proxy Helm chart using the ingress.yaml file that you have created

made me think about the Ingress `I have created`, not the one the the chart creates. If you didn't tell me above I wouldn't have properly understood this
>The Helm chart creates a reverse proxy 

as 
>The Neo4j Helm charts provide a Helm chart that allows you to use a Kubernetes Ingress to access Neo4j on port :80 or :443

helped me thinking I could use the one I create.

Fortunately you're very kind and helped me out clarifying it. Many thanks.

Now this part still confuses me:
>helm install rp neo4j/neo4j-reverse-proxy -f /path/to/your/ingress.yaml

this points to the ingress `I created` again.. so you see? New confusion emerges..

Thank you very much again

**Comment by harshitsinghvi22** [comment]
> Install the Reverse proxy Helm chart using the ingress.yaml file that you have created

To be honest here , the documentation first explains the ingress.yaml to you through the [link](https://neo4j.com/docs/operations-manual/current/kubernetes/accessing-neo4j-ingress/#_configure_the_kubernetes_ingress) and then asks you to install the helm chart so I am not sure why you would understand it as to use your own ingress . It clearly states ingress.yaml

You need to use the following steps to create a yaml based on the port you want to access your neo4j on 
For 443 - https://neo4j.com/docs/operations-manual/current/kubernetes/accessing-neo4j-ingress/#_configure_the_ingress_yaml_file_to_access_neo4j_on_port_443
For 80 - https://neo4j.com/docs/operations-manual/current/kubernetes/accessing-neo4j-ingress/#_configure_the_ingress_yaml_file_to_access_neo4j_on_port_80

> Now this part still confuses me: helm install rp neo4j/neo4j-reverse-proxy -f /path/to/your/ingress.yaml. this points to the ingress I created again.. so you see? New confusion emerges..

Again, you are reading it incorrectly , /path/to/your/ingress.yaml points to the path of your ingress.yaml **file** and not the ingress.

**Comment by vinnytwice** [comment]
>To be honest here , the documentation first explains the ingress.yaml to you through the [link](https://neo4j.com/docs/operations-manual/current/kubernetes/accessing-neo4j-ingress/#_configure_the_kubernetes_ingress) and then asks you to install the helm chart so I am not sure why you would understand it as to use your own ingress . It clearly states ingress.yaml

I must be dumb then..but then again, I don't mean to be rude, but I see the documentation misleading instead.
 `helm install rp neo4j/neo4j-reverse-proxy -f /path/to/your/ingress.yaml` as I read it means I know the path to an `ingress.yaml` file as I have to specify it when installing the chart. But ( as you also stated above) the `ingress.yaml` gets created by the chart as in fact I see it in the chart's `templates` folder so I shouldn't have to specify any path to it when I  install the chart.
It should just get it's values from the chart's values.yaml file as we configure it, ( as in fact it does) so the command to install the chart reported in the docs should only be `helm install rp neo4j/neo4j-reverse-proxy`.
 
 
  Otherwise to what other `ingress.yaml` file could the `helm install rp neo4j/neo4j-reverse-proxy -f /path/to/your/ingress.yaml` command in the docs refer to? The only other one is the one `I` created, not the chart, and for which I do know w the path indeed. That's why I thought of `my` ingress.yaml and not the one created by the chart.
  
  You see, throughout the entire docs the chart's `ingress.yaml` file is referred to as `your ingress.yaml` or the `the ingress.yaml you created`, not as `the chart's ingress.yaml` or `the chart's ingress.yaml that you configured` , and you're doing it again in 
  >Again, you are reading it incorrectly , /path/to/your/ingress.yaml points to the path of your ingress.yaml file and not the ingress.
  
 Which one is `your ingress` and which one is the one at the end of the sentence? `your ingress` is the one created by the chart and the one at the end of the sentence the one I created? then you're using the wrong adjectives as the docs..
 
  
  That's where the whole confusion begins and ends.
  
Hope you see my point
Thanks

**Comment by harshitsinghvi22** [comment]
> But ( as you also stated above) the `ingress.yaml` gets created by the chart as in fact I see it in the chart's `templates` folder so I shouldn't have to specify any path to it when I install the chart.

No , i have never mentioned that ingres.yaml is created by the chart. I clearly mentioned "You need to use the following steps to create a yaml based on the port you want to access your neo4j on"

But , I understand the confusion here. The ingress.yaml thats referred to in the documentation is the values.yaml and not the ingress.yaml in the templates folder. The -f flag with helm indicates values.yaml and not the ingress.yaml which deploys the ingress resource. I will get this updated to named to ingress-values.yaml to avoid any further confusion.

Hope this clarifies :-)

**Comment by vinnytwice** [comment]
>No , i have never mentioned that ingres.yaml is created by the chart.

I was referring to this part below

> The helm chart itself creates an ingress which allows two ports 80/443 which then redirects traffic to 7687 and 7474.

>Hope this clarifies :-) 

It didn't lol.. I thought I had it but your last message confused me.
(When I thought I was out, they pull me back in!) lol

let me recap..

1. The chart deploys an Ingress which is used to connect to Neo4j on either port 80 or 443. 
2. This is the ingress.yaml in the templates folder, which is configured form the chart's values portion.
```
ingress:
    enabled: true
    #default value is nginx. It can be either nginx or haproxy
    className: nginx
    annotations: {}
#      "demo": "value"
#      "demo2": "value2"
    tls:
      enabled: false
      config: []
#      - secretName: "demo2"
#        hosts:
#          - localhost
```


3. The docs refer to this ingress when they mention:
```
Configure the Kubernetes Ingress

Configure the ingress.yaml file that you will use to install the Reverse proxy Helm chart.
Configure the ingress.yaml file to access Neo4j on port :443

The following example shows how to configure the ingress.yaml file to access Neo4j on port :443:
Create a Kubernetes secret containing the Ingress self-signed certificates and then create the ingress.yaml file.
Create a directory for the Ingress self-signed certificates:
mkdir certs
cd certs
Create Ingress self-signed certificates:
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ingress.key -out ingress.cert -subj "/CN=localhost/O=neo4j" -addext "subjectAltName = DNS:localhost"
Create Kubernetes secret using the Ingress self-signed certificates:
kubectl create secret tls ingress-cert --key /path/to/your/certs/ingress.key --cert /path/to/your/certs/ingress.cert
Configure the ingress.yaml file with the correct values for the serviceName and secretName. Ensure that the secretName is the same as the one created in the previous step. Enable TLS by setting tls.enabled to true.
reverseProxy:
    image: neo4j/helm-charts-reverse-proxy:5.12.0
    serviceName: "standalone-admin"
    ingress:
        enabled: true
        tls:
            enabled: true
            config:
                - secretName: ingress-cert
                  hosts:
                    - localhost
Configure the ingress.yaml file to access Neo4j on port :80

Alternatively, if you want to access Neo4j on port :80, leave tls.enabled with its default value false, and create the ingress.yaml file with the following content:
reverseProxy:
    image: neo4j/helm-charts-reverse-proxy:5.12.0
    serviceName: "standalone-admin"
    ingress:
        enabled: true
        tls:
            enabled: false
            
```
So far so good. Now what's not clear yet.
>The -f flag with helm indicates values.yaml and not the ingress.yaml which deploys the ingress resource. I will get this updated to named to ingress-values.yaml to avoid any further confusion.

So the `helm install rp neo4j/neo4j-reverse-proxy -f /path/to/your/ingress.yaml` command in the docs should have been `helm install rp neo4j/neo4j-reverse-proxy -f /path/to/your/values.yaml` as in fact you can override the chart's values.yaml with your own local file.

This time it should be all clear :-)
Thanks for your patience.

**Comment by harshitsinghvi22** [comment]
> So the `helm install rp neo4j/neo4j-reverse-proxy -f /path/to/your/ingress.yaml` command in the docs should have been `helm install rp neo4j/neo4j-reverse-proxy -f /path/to/your/values.yaml` as in fact you can override the chart's values.yaml with your own local file.

Yes, i have requested the change and should be done pretty soon.

Yes, the docs refers to values.yaml as ingress.yaml and not the kubernetes resource "ingress"


> > The helm chart itself creates an ingress which allows two ports 80/443 which then redirects traffic to 7687 and 7474.
> 
> > Hope this clarifies :-)
> 
> It didn't lol.. I thought I had it but your last message confused me.

The neo4j-reverse-proxy helm chart does create a Kuberenetes ingress . I am assuming here when you say "It didn't lol" you mean the kubernetes ingress resource is not created when you deploy the helm chart. I might be wrong here in understanding but still clarifying :-) 

> * The chart deploys an Ingress which is used to connect to Neo4j on either port 80 or 443.

Yes 

> * This is the ingress.yaml in the templates folder, which is configured form the chart's values portion.

Yes

**Comment by vinnytwice** [comment]
@harshitsinghvi22 Hi, it's all clear now. Thank you very much again for the support and patience, you're a good man.
Cheers

**Comment by harshitsinghvi22** [comment]
I am glad @vinnytwice this is clear now. Thanks for putting up with me . Cheers
